### PR TITLE
Reorganize data files

### PR DESCRIPTION
**Pull request by bsaul**

### CODE REVIEW

**Comment by bsaul** [comment]
@IJBG - do we use `inst/extdata/IBP-AOS-LIST21.csv` file, I see the `inst/create_spec_code_frame.R` script, but I don't see that we actually use it.

**Comment by bsaul** [comment]
> What is the `inst/extdata/species_comments_errors.csv` file? It appears empty except for column headers.

Oh, I see it's used as temp file in `process_species_comments`. 

Is this a file that we need to keep in the repo?

**Comment by IJBG** [comment]
I haven't used `inst/extdata/IBP-AOS-LIST21.csv` anywhere.

Yes, I just realized myself that species_comments_errors is empty right now - there are 37 errors that should be in there. It will be filled in with data while I'm making the species_comments .csv - I need to use it to create the stop_level data (for now)

**Comment by IJBG** [comment]
But, it can be added to the .gitignore I think, since I just need it when actively working on species_comments and not at other times.

**Comment by bsaul** [comment]
@IJBG  - I think is enough change for one PR and ready for review. It's mostly renaming/moving data files (and deleting some) and updating the `data-pipeline.md` file where relevant.

Sorry about these big diffs - I think there will be a few PRs like this as we reorganize.

**Review by IJBG — APPROVED** [review]
Yeah, looks good! I like the new organization structure in inst/

**Pull request merged**
