### PR TITLE
Remove 2005 duplicates from chatham csv

### LINKED ISSUE #28: Errant counts in Chatham route 6 in 2005?
@ahhurlbert - Chatham route 6 has a big spike in counts in 2005. I'm seeing this spike for multiple species, so I'm wondering if double counting happened in the data scraping process. There's a spike in 2010 too, but I'm not seeing this spike for multiple species.

```
> 
> dt %>%
+   filter(mbbs_county == "chatham", route_num == 6) %>%
  group_by(year) %>%
+   group_by(year) %>%
+   summarize(count = sum(count))
# A tibble: 15 × 2
    year count
   <dbl> <dbl>
 1  2000   318
 2  2001   352
 3  2002   272
 4  2003   221
 5  2004   193
 6  2005   726 <-- here
 7  2006   288
 8  2007   256
 9  2008   289
10  2009   335
11  2010   628
12  2018   318
13  2019   253
14  2020   277
15  2021   276
```

### PR DESCRIPTION
**Pull request by bsaul**
Closes #28

### CODE REVIEW

**Comment by bsaul** [comment]
@ahhurlbert - assigning review to you. Feel free to merge if it looks good.

**Comment by bsaul** [comment]
I bumped the version using the old scheme, but note that in #29 we'll moving to a date-based version convention.

**Comment by ahhurlbert** [comment]
Whoops, looks like the Version in DESCRIPTION is conflicting.

Which versioning system did we settle on, years (Version: 2022.0) or incrementing from what was there before (Version: 0.4.0.0)?

**Comment by ahhurlbert** [comment]
Ah, right. Skipped reading the comment.

**Pull request merged**
